swagger: "2.0"
info:
  description: "HTTP Thermostat API"
  version: "1.0.0"
  title: "HTTP Thermostat"
host: "localhost:8000"
basePath: "/api"
tags:
- name: "http-thermostat"
schemes:
- "http"
paths:
  /status:
    get:
      tags:
      - "http-thermostat"
      summary: "Get any thermostat info"
      description: "Get any thermostat info"
      operationId: "status"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "xebug_session_start"
        type: string
      responses:
        200:
          description: "OK"
          schema:
             $ref: '#/definitions/StatusValue'
  "/targetHeatingCoolingState/{state}":
    parameters:
      - name: state
        in: path
        type: number
    get:
      summary: "Set heating/cooling state"
      description: "Set heating/cooling state"
      tags:
      - "http-thermostat"
      operationId: targetHeatingCoolingState
      responses:
        201:
          description: "OK"
  "/targetTemperature/{temp}":
    parameters:
      - name: temp
        in: path
        type: number
    get:
      summary: "Set target temperature"
      description: "Set target temperature"
      tags:
      - "http-thermostat"
      operationId: targetTemperature
      responses:
        201:
          description: "OK"
  "/targetRelativeHumidity/{humidity}":
    parameters:
      - name: humidity
        in: path
        type: number
    get:
      summary: "Set target relative humidity"
      description: "Set target relative humidity"
      tags:
      - "http-thermostat"
      operationId: targetRelativeHumidity
      responses:
        201:
          description: "OK"
definitions:
  StatusValue:
      type: object
      properties:
        targetHeatingCoolingState:
          type: integer
        targetTemperature:
          type: number
        targetRelativeHumidity:
          type: number
        currentHeatingCoolingState:
          type: integer
        currentTemperature:
          type: number
        currentRelativeHumidity:
          type: number


