<?php
/**
 * HTTP Thermostat
 * HTTP Thermostat API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\RESTfulAPI\Codegen\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

abstract class HttpthermostatApiBase extends Controller
{
    /**
     * Operation status
     *
     * Get any thermostat info.
     *
     * @param Request $request request object (required)
     *
     * @return \Illuminate\Http\Response
     */
    public function statusWithValidate(Request $request)
    {
        $this->statusValidate($request);
        return $this->status($request);
    }

    /**
     * Validate status
     *
     * Get any thermostat info.
     *
     * @param Request $request request object (required)
     *
     */
    protected function statusValidate(Request $request)
    {
        // path params validation

        // not path params validation
    }

    /**
     * Operation targetHeatingCoolingState
     *
     * Set heating/cooling state.
     *
     * @param Request $request request object (required)
     * @param float $state  (required)
     *
     * @return \Illuminate\Http\Response
     */
    public function targetHeatingCoolingStateWithValidate(Request $request, $state)
    {
        $this->targetHeatingCoolingStateValidate($request, $state);
        return $this->targetHeatingCoolingState($request, $state);
    }

    /**
     * Validate targetHeatingCoolingState
     *
     * Set heating/cooling state.
     *
     * @param Request $request request object (required)
     * @param float $state  (required)
     *
     */
    protected function targetHeatingCoolingStateValidate(Request $request, $state)
    {
        // path params validation

        // not path params validation
    }

    /**
     * Operation targetRelativeHumidity
     *
     * Set target relative humidity.
     *
     * @param Request $request request object (required)
     * @param float $humidity  (required)
     *
     * @return \Illuminate\Http\Response
     */
    public function targetRelativeHumidityWithValidate(Request $request, $humidity)
    {
        $this->targetRelativeHumidityValidate($request, $humidity);
        return $this->targetRelativeHumidity($request, $humidity);
    }

    /**
     * Validate targetRelativeHumidity
     *
     * Set target relative humidity.
     *
     * @param Request $request request object (required)
     * @param float $humidity  (required)
     *
     */
    protected function targetRelativeHumidityValidate(Request $request, $humidity)
    {
        // path params validation

        // not path params validation
    }

    /**
     * Operation targetTemperature
     *
     * Set target temperature.
     *
     * @param Request $request request object (required)
     * @param float $temp  (required)
     *
     * @return \Illuminate\Http\Response
     */
    public function targetTemperatureWithValidate(Request $request, $temp)
    {
        $this->targetTemperatureValidate($request, $temp);
        return $this->targetTemperature($request, $temp);
    }

    /**
     * Validate targetTemperature
     *
     * Set target temperature.
     *
     * @param Request $request request object (required)
     * @param float $temp  (required)
     *
     */
    protected function targetTemperatureValidate(Request $request, $temp)
    {
        // path params validation

        // not path params validation
    }

    abstract protected function status(Request $request);
    abstract protected function targetHeatingCoolingState(Request $request, $state);
    abstract protected function targetRelativeHumidity(Request $request, $humidity);
    abstract protected function targetTemperature(Request $request, $temp);
}
