<?php
/**
 * HTTP Thermostat
 * HTTP Thermostat API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\RESTfulAPI\Models;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\RESTfulAPI\Codegen\Models\StatusValueBase;

class StatusValue extends StatusValueBase
{
    /**
     * table name.
     *
     * @var string
     */
    protected $table = 'status_value_table';

    /**
     * hidden attributes.
     *
     * @var string[]
     */
    //protected $hidden = [];

    /**
     * update timestamps.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * column names for dates.
     *
     * @var string
     */
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    /**
     * name of database connection.
     *
     * @var string
     */
    //protected $connection = 'connection-name';
}
